- .github/workflows/build.yml
- .github/workflows/publish.yml
- .gitignore
- .prettierrc
- jest.config.js
- package-lock.json
- package.json
- src/index.ts
- src/logger/LogLevel.ts
- src/logger/LogOutput.ts
- src/logger/Logger.spec.ts
- src/logger/Logger.ts
- src/logger/index.ts
- src/logger/isLowerThanOrEqualTo.spec.ts
- src/logger/isLowerThanOrEqualTo.ts
- tsconfig.json
- webpack.config.js
> chore(*): initial project setup

- src/types/target.ts
Target type needs update to run for all sasjs-cli tests.
> fix: Target type updated

- README.md
BREAKING CHANGE: SASj 2.0 release
> BREAKING CHANGE: SASj 2.0 release

- src/types/config.ts
- src/types/target.ts
- src/types/targetValidators.spec.ts
- src/types/targetValidators.ts
[docConfig modifications](https://github.com/sasjs/cli/issues/449)
Add docConfig to Target also
New attribute `dataControllerUrl` added to `docConfig`, and added to Target.
mocked tests
server tests
> feat: docConfig updated and also added to Target

- src/types/target.ts
- src/types/targetValidators.spec.ts
- src/types/targetValidators.ts
https://github.com/sasjs/cli/issues/455
Added `allowInsecureRequests` to target
> feat: allowInsecureRequests boolean in Target

- src/types/config.ts
- src/types/target.spec.ts
- src/types/targetValidators.spec.ts
- src/types/targetValidators.ts
Link any related issue(s) in this section.
> fix(docConfig): disableLineage -> enableLineage

- .prettierrc
- src/types/sasjsconfig-schema.json
Link any related issue(s) in this section.
> chore: prettier config reverted

- src/types/sasjsconfig-schema.json
fixing linting
- [x ] Code is formatted correctly (`npm run lint:fix`).
> fix: prettier

- src/file/file.spec.ts
- src/file/file.ts
- src/file/index.ts
- src/index.ts
Fixes https://github.com/sasjs/utils/issues/3
Add utils for file system operations.
* Added `file` utils module.
* Extracted file utils code from CLI and converted to use `fs.promises` module.
* Added unit tests.
> feat(file-utils): added file handling functions

- src/types/sasjsconfig-schema.json
- src/types/target.spec.ts
- src/types/target.ts
[unnecessary attributes to the target](https://github.com/sasjs/cli/issues/552)
Export function to have existing values only
Updated `target.ts`
- Added new function `toJsonNoDefaults`
mocked:
> fix: target to json without default values

- src/types/targetValidators.spec.ts
> chore(targetValidators): fixed 'validateTestConfig' tests

- package-lock.json
- package.json
- src/file/file.ts
- src/formatter/index.ts
- src/formatter/string.spec.ts
- src/formatter/string.ts
- src/logger/Logger.spec.ts
- src/logger/logger.ts
https://github.com/sasjs/cli/issues/607
Create utility outputting tables to the console.
1. Extended `Logger`.
> feat(logger): added table method to Logger class

- src/file/index.ts
Export `pathSepEscaped` utility.
> chore(file): exported pathSepEscaped utility

- package-lock.json
- package.json
- src/file/index.ts
> fix(version): updated ts version to bump @sasjs/utils version

- src/types/macro.spec.ts
- src/types/macro.ts
Add `isMacroVars` type guard.
Mocked:
> feat(macro): added isMacroVars type guard

- src/file/file.ts
- src/file/index.ts
- src/file/spec/file.spec.ts
Move cli file function `listIniFilesInFolder` to `sasjs/utils` 
Updated `file/file.ts` and tests
> feat: new file function listIniFilesInFolder

- src/types/extraResponseAttributes.ts
Adding extra response attributes type
> Extra response attributes

- src/file/file.ts
- src/file/index.ts
No issues.
Add file function to read file in binary mode.
Updated `src/file/file.ts` 
- Added `readFileBinary`
> feat: read file in binary mode

- src/types/target.spec.ts
- src/types/target.ts
No linked issue.
Remove incorrect default values used to initialise `authConfig`.
* Remove incorrect default values used to initialise `authConfig`.
* Update test.
> fix(auth-config): remove incorrect default values

- src/auth/auth.spec.ts
- src/auth/auth.ts
None.
Add function to check if a given token has expired.
* Added `hasTokenExpired` function.
* Added tests for function.
> feat(auth): add token expiry check function

- .github/workflows/build.yml
- package-lock.json
- package.json
- src/file/file.ts
- src/file/spec/file.spec.ts
https://github.com/sasjs/cli/issues/587
* Add function to determine if a given path is a file or folder.
* Fix issue with deleting non-empty folders.
* Add tests.
* Added function to determine if a given path is a file or folder.
* Fixed issue with deleting non-empty folders.
* Added tests.
* Set minimum node version to 15 (I will change this across all the repos in the coming days).
> feat(is-folder): determine if a given path is a file or a folder

- src/types/sasjsconfig-schema.json
No issue to link.
Update json schema for `httpsAgentOptions`
> fix: updated json schema for httpsAgentOptions

- src/sasjsCli/getDependencyPaths.ts
- Add a comment about the compilation process.
- Refactor `getDependencyPaths` function.
- Changed error throwing condition to throw if `sourcePath` is in `macroFolders` only.
Mocked:
> chore: refactor and add comment to getDependencyPaths

- src/utils/index.ts
- src/utils/utils.spec.ts
- src/utils/utils.ts
Adding `isLinux` along the existing `isWindows` check function.
> isLinux function

- src/types/target.spec.ts
- src/types/target.ts
> fix(target): remove unwanted if else statements regarding deployConfig from toJson method

- src/utils/index.ts
> fix: export escapeWinSlashes function from index file

- src/types/config.ts
- src/types/target.ts
- src/types/targetValidators.spec.ts
- src/types/targetValidators.ts
* add a new `syncDirectories` attribute to the target class
* add syncDirectories validator function
> fix: add syncDirectories config to target

- src/fs/sync.ts
- src/utils/utils.ts
- tsconfig.json
> fix: replace all backslashes with forward slash

- src/types/sasjsconfig-schema.json
> fix: update sasjsconfig-schema.json

- src/time/index.ts
- src/time/timestamp.spec.ts
- src/time/timestamp.ts
> feat: add a utility for converting seconds to Hour, minutes and seconds

- src/utils/spec/url.spec.ts
> chore: cleanup

- .github/workflows/assign-reviewer.yml
- .github/workflows/publish.yml
- Use `GITHUB_TOKEN` as an access token in github actions.
- Updated `.github/workflows/assign-reviewer.yml`.
- Updated `.github/workflows/publish.yml`.
> chore(github-actions): fixed access token

- package-lock.json
- package.json
- src/file/file.ts
Link any related issue(s) in this section.
Update rimraf to a new, maintained, version
rimraf doesn't accept a callback anymore => changed to the new interface
> Update rimraf to version 5

- package-lock.json
- package.json
- src/file/file.ts
> Removing rimraf
