.vscode/settings.json
jest.config.js
package.json
src/input/index.ts
src/input/readAndValidateInput.spec.ts
src/input/readAndValidateInput.ts
src/input/validators.spec.ts
src/input/validators.ts
src/logger/Logger.spec.ts
src/logger/isLowerThanOrEqualTo.spec.ts

https://github.com/sasjs/utils/issues/8
Improve input functions - remove the need to pass in `fieldName`, and do some additional validation before returning the value.
* Added `validators.ts` which has common validation functions.
* Removed `fieldName` argument from all functions.
* Validated the returned value before resolving.
* Added tests for all scenarios.
* Enforced code coverage metrics.

fix(input): improve input APIs, add unit tests, enforce coverage metrics

---

jest.config.js
src/logger/index.ts
src/logger/isLowerThanOrEqualTo.spec.ts
src/logger/isLowerThanOrEqualTo.ts
src/logger/logLevel.ts
src/logger/logger.ts
src/types/config.ts
src/types/index.ts
src/types/target.spec.ts
src/types/target.ts
src/types/targetValidators.spec.ts
src/types/targetValidators.ts

Closes https://github.com/sasjs/utils/issues/10
Create new model for `Target` and validate all the fields.
* Created interfaces for various types of config.
* Created `Target` class that parses and validates the JSON in the constructor.
* Added functions to validate each part of the JSON.
* Added nearly 100 unit tests for various different combinations of values.

feat(target): create new model for target

---

src/error/errorModifier.spec.ts
src/error/errorModifier.ts
src/error/index.ts
src/types/index.ts
src/types/serverError.ts

Create a utility that will append message prefix to error object.
1. `errorModifier.ts`
2. `errorModifier.spec.ts`

feat(error-modifier): added prefixMessage utility

---

src/types/targetValidators.spec.ts
src/types/targetValidators.ts

https://github.com/sasjs/cli/issues/389
Prevent errors being thrown when the `serverUrl` is `null` or `undefined`.
* Removed validation error clause for `serverUrl`.

fix(server-url): set serverUrl to empty string when null or undefined

---

src/types/target.spec.ts
src/types/target.ts

https://github.com/sasjs/utils/issues/17
Add server-specific attributes to the saved JSON.
* Conditionally add attributes to JSON based on server type.
* Add tests to cover the new scenarios.

fix(target): include server-specific attributes in target JSON

---

src/types/config.ts

https://github.com/sasjs/cli/issues/415
Needs to have `DocConfig` object at root level in configuration
Added `DocConfig` to `config.ts`

feat(DocConfig): added 'DocConfig' for Configuration

---

package-lock.json
package.json
src/input/readAndValidateInput.spec.ts
src/input/readAndValidateInput.ts

https://github.com/sasjs/utils/issues/22
Exit quietly with a one-line message when the user presses `Ctrl+C`.
* Added `onCancel` callback to `prompts`.
* Made `value` attribute mandatory for choices.
* Fixed tests.
* Made `@types/prompts` a regular dependency so that it can be used by the CLI to recognise `prompts` typings correctly.

fix(handle-cancel): exit gracefully when user cancels input

---

src/types/config.ts
src/types/target.ts
src/types/targetValidators.spec.ts
src/types/targetValidators.ts

1. Make all properties of `docConfig` optional, 
- `docConfig` is present at `root` and `Target` levels, 
- `docConfig.xyz` of Target has precedence over root level's if present, so defaults set to undefined
2. added `disableLineage` as per [issue](https://github.com/sasjs/cli/issues/478)

fix: docConfig properties are made optional + disableLineage is added

---

.github/workflows/build.yml
src/input/readAndValidateInput.spec.ts
src/types/config.ts
src/types/target.spec.ts
src/types/target.ts
src/types/targetValidators.spec.ts
src/types/targetValidators.ts

https://github.com/sasjs/utils/issues/27
Make the stream service name configurable
* Added `streamServiceName` to `streamConfig`.
* Added tests.
* Added missing tests for `docConfig` and `onCancel`.

feat(stream-config): make stream service name configurable

---

src/types/target.spec.ts
src/types/target.ts

Fixes https://github.com/sasjs/utils/issues/30
Add the ability to set a target as default.
* Added `isDefault` boolean property to target.

feat(default-target): add ability to set target as default

---

src/types/target.spec.ts
src/types/target.ts

No linked issue.
Include `isDefault` property in target JSON.
* Included `isDefault` property in target JSON.
* Added test.

fix(is-default): include flag in target JSON

---

src/input/readAndValidateInput.ts

When updating current target through `sasjs add target`, need to have default for existing target's `serverUrl`

fix: default value for url

---

src/types/configuration.ts
src/types/index.ts
src/types/target.spec.ts
src/types/target.ts

https://github.com/sasjs/utils/issues/30
Add `defaultTarget` to top-level configuration object.
* Added interface for `Configuration` - moved over from CLI codebase.
* Changed `TargetInterface` to `TargetJson` and made it public.
* Added `defaultTarget` string field to `Configuration`.
* Removed `isDefault` field from individual targets.

fix(default-target): add default target field to configuration

---

src/types/config.ts

https://github.com/sasjs/cli/issues/551
Add `doxyContent` attribute to `docConfig`
```
doxyContent?: {
favIcon: string
footer: string
header: string
layout: string
logo: string
readMe: string
stylesheet: string
}
```
updated `config.ts`

chore: added doxy content variabls to docConfig for customization

---

src/types/config.ts

Make doxygen content folder's path customizable
Added `path` to `docConfig.doxyContent`

fix(docs): added path to docConfig

---

.gitpod.yml
.prettierrc
src/types/config.ts
src/types/sasjsconfig-schema.json
src/types/target.spec.ts
src/types/target.ts
src/types/targetValidators.spec.ts
src/types/targetValidators.ts

https://github.com/sasjs/cli/issues/560
BUILD folder should be configurable.
`buildOutputFolder` added to `buildConfig`

feat: build output folder is configurable

---

src/types/config.ts
src/types/target.spec.ts
src/types/target.ts
src/types/targetValidators.spec.ts
src/types/targetValidators.ts

https://github.com/sasjs/cli/issues/569
Resutls folder should be configurable.
`buildResultsFolder` added to `buildConfig`

feat(buildConfig): sasjsresults folder added

---

src/file/file.spec.ts
src/file/file.ts

Required for https://github.com/sasjs/lint/issues/1.
Add the ability to list subfolders in a given folder path.
* Added `listSubFoldersInFolder` function.
* Added test.

feat(file): add function that lists subfolders

---

package-lock.json
package.json

Fix `readAndValidateInput` utility.
Moved `@types/prompts` from `devDependencies` to `dependencies`

fix(prompt): fixed prompt types dependencies

---

.git-hooks/commit-msg
package.json
src/input/validators.spec.ts
src/types/targetValidators.spec.ts

Enable pre-commit git hook enforcing conventional commits.
1. Added `.git-hooks/commit-msg`.
2. Added `postinstall` script to `package.json`

feat(git): enabled git hook enforcing conventional commits

---

src/utils/index.ts
src/utils/url.spec.ts
src/utils/url.ts

https://github.com/sasjs/cli/issues/688
Create a utility that returns URL origin.
Mocked:

feat: added urlOrigin utility

---

package-lock.json
package.json
src/file/file.ts

Remove `fs` package
> This package name is not currently in use, but was formerly occupied by another package. To avoid malicious use, npm is hanging on to the package name, but loosely, and we'll probably give it to you if you want it.
Replaced `fs` with `fs-extra`

fix: replaced 'fs' with 'fs-extra'

---

src/file/index.ts

Added `pathSepEscaped` to exported list

fix: added 'pathSepEscaped' to export list

---

src/file/file.ts
src/file/index.ts

Moved `getRealPath` from `sasjs/cli` to `utils/file`

fix: moved 'getRealPath' from sasjs/cli

---

package-lock.json
package.json
src/auth/auth.spec.ts
src/auth/auth.ts
src/auth/index.ts
src/index.ts

https://github.com/sasjs/adapter/issues/444
Add functions to check for expiry of access and refresh tokens.
* Added `auth` utils.
* Added unit tests.

feat(token-expiry): add utils to check for token expiry

---

src/types/config.ts
src/types/target.spec.ts
src/types/target.ts
src/types/targetValidators.spec.ts
src/types/targetValidators.ts
src/utils/base64.spec.ts
src/utils/base64.ts
src/utils/index.ts

The intention is to add authconfig for sas9 server type add encoding decoding utility.

feat: add auth config for sas9 in target

---

package.json

NPM Postinstall command is not supported in windows CMD
Also move it to `prepare` instead of `postinstall`
Changed posinstall command from `[ -d .git ] && ...` to `git rev-parse --git-dir && ...`

fix: postinstall support windows CMD/Powershell

---

package-lock.json
package.json

`@types/fs-extra` failed to declare types as a development dependency.
Moved `@types/fs-extra` from `devDependencies` to `dependencies`.
Mocked:

fix(deps): moved fs-extra types to deps to resolve declaration issue

---

src/file/file.ts

Fixes https://github.com/sasjs/utils/issues/105.
When running the `@sasjs/cli` tests locally, there are a number of random failures on cleanup steps, which are caused by folders not being empty. This is quite an annoyance as the tests take a long time to run, and random failures which have nothing to do with the current changes lead to a lot of time wastage.
Changed `deleteFile` and `deleteFolder` functions to use the `remove` function from `fs-extra`.

fix(file-utils): use remove functions from fs-extra

---

package-lock.json
package.json
src/input/readAndValidateInput.spec.ts

Update dependencies:
- typescript from 4.3.5 to 4.4.2 
- @types/jest from 26.0.24 to 27.0.1
Removed redundant `done` callback from `readAndValidateInput.spec.ts`.
Mocked:
Server:

chore(deps): update dependencies

---

src/sasjsCli/getInitTerm.spec.ts
src/sasjsCli/getInitTerm.ts

No issue to link.
Incorrect term header is present.
Fixed code in `getInitTerm.ts` and added specs to check content + header for `init` and `term`

fix: get correct term header while extracting dependencies

---

src/file/file.ts

No issue to link.
Write file with provided encoding
updated writeFile function with optional encoding.

fix: writeFile with base64 string

---

src/compileTree/compileTree.ts
src/file/spec/file.spec.ts
src/formatter/index.ts
src/formatter/regexp.spec.ts
src/formatter/regexp.ts
src/utils/utils.spec.ts
src/utils/utils.ts

- Fix `removeHeader` for windows systems.
- Added `isWindows` util.
- Added `newLine` util.

fix(compile-tree): fixed CompileTree and add isWindows and newLine utils

---

src/formatter/regexp.spec.ts
src/formatter/regexp.ts

Fix `cli.spec.ts` in `@sasjs/cli`.
- Used `process.platform` instead of `isWindows` utility in `newLine` utility

fix(regexp): fixed newLine utility

---

src/compileTree/compileTree.ts
src/sasjsCli/getInitTerm.spec.ts
src/sasjsCli/getInitTerm.ts
src/sasjsCli/loadDependenciesFile.ts

https://github.com/sasjs/cli/issues/1164
- Fix compilation issues detected in `@sasjs/core`
- Made `removeHeader` less greedy.
- Changed `getProgram` to also return `CompileTreeLeaf` that can be used to get the dependencies.
- Adjusted unit tests.
- [] All `sasjs-cli` unit tests are passing (`npm test`).
Mocked:
- [] Reviewer is assigned.

Compile Tree improvements

---

src/types/fileTree.ts

No issue to link
[tsoa](https://www.npmjs.com/package/tsoa) swagger docs generation cannot parse Type define with `extends`.
Reverted code to explicit types:
From 
```
export interface FileTree {
members: (FolderMember | ServiceMember | FileMember)[]
}
export interface FolderMember extends FileTree {
name: string
type: MemberType.folder
}
```
To
```
export interface FolderMember {
name: string
type: MemberType.folder
members: (FolderMember | ServiceMember | FileMember)[]
}
export interface FileTree {
members: (FolderMember | ServiceMember | FileMember)[]
}
```

fix(types): define explicit types

---

src/types/sasjsconfig-schema.json

https://github.com/sasjs/cli/pull/1214
Updating sasjsconfig.json schema for syncFolder attribute
Updated the json file

fix: schema for sasjsconfig with new syncFolder attribute

---

src/utils/utils.spec.ts
src/utils/utils.ts

* replace single backslash with a double backslash if `process.platform` is `win32`

feat: add utility getOSSpecificPath

---

src/fs/generateCompileProgram.ts
src/fs/internal/helper.ts
src/fs/spec/createFSCompileProgram.spec.ts
src/fs/sync.ts
src/types/sasjsconfig-schema.json
src/utils/index.ts
src/utils/utils.ts

closes #214
* sas code requires forward slashes as the path separators in file or folder paths. So replaced os specific path separators with a forward slash `/`.
* created a utility that replaces path separator in a string with `/`

fix: always use / as path separator in the generated SAS code

---

src/fs/generateCompileProgram.ts
src/fs/sync.ts

* sasjs fs sync and sasjs fs compile needs some more macros as dependencies in generated program

fix: add more macro dependencies to generated programs

---

src/fs/hash.ts
src/fs/index.ts
src/fs/spec/hash.spec.ts

Move extract hash array function from cli and extension to utils

fix: move extractHashArray function to utils

---

src/file/file.ts
src/file/index.ts
src/file/spec/file.spec.ts

* Add a new helper method in the file module which will list all SAS files in a folder.
* This method has the ability to fetch files from nested folders
* also has the ability to ignore some specified folders while extracting files in a nested approach

feat: add a new method listSasFilesInFolder

---

src/types/targetValidators.spec.ts
src/types/targetValidators.ts

fix: update error message when webSourcePath is missing and streamConfig is true

---

package-lock.json
package.json
src/file/csvFile.ts

* csv-stringify was a bit problematic in sasjs/cli. So, replaced it with fast-csv/format

fix: replace package csv-stringify with @fast-csv/format

---

src/types/config.ts
src/types/configuration.ts
src/types/target.spec.ts
src/types/target.ts
src/types/targetValidators.spec.ts
src/types/targetValidators.ts

* remove buildOutputFolder and buildResultsFolder from the build config
* add sasjsBuildFolder and sasjsResultsFolder to the top level of configuration and targetJson interfaces

feat: add sasjsBuildFolder and sasjsResultsFolder to configuration

---

src/compileTree/compileTree.spec.ts
src/compileTree/compileTree.ts
src/sasjsCli/getDependencies.ts
src/sasjsCli/getDependencyPaths.ts

Related to https://github.com/sasjs/cli/issues/1338
Throw an error during the compilation if `<h4> SAS Includes </h4>` or `<h4> Binary Files </h4>` headers were detected in the content of the `Macro`.
- Added `validateDependency` method to `CompileTree` class.
- Added unit test to cover `validateDependency`.

feat(compile): added validateDependency method
